default:
  image: node:18-alpine

stages:
  - build
  - lint
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# -------------- BUILD STAGE --------------
build:
  stage: build
  image: docker:25
  services:
    - name: docker:25-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}"
  only:
    - development
    - main

# -------------- LINT STAGE --------------
lint:
  stage: lint
  script:
    - echo "Running ESLint..."
    - npm install
    - npm run lint
  only:
    - development
    - main

# -------------- TEST STAGE --------------
test:
  stage: test
  script:
    - echo "Running Jest tests..."
    - npm install
    - npm run test
  artifacts:
    name: "coverage-${CI_COMMIT_REF_NAME}"
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - development
    - main

# -------------- DEPLOY STAGE --------------
deploy:
  stage: deploy
  image: docker:25
  services:
    - name: docker:25-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - |
      if [ "$CI_COMMIT_REF_NAME" = "development" ]; then
        export TAG="development"
      elif [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        export TAG="latest"
      else
        export TAG="$CI_COMMIT_REF_NAME"
      fi
  script:
    - docker pull "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}"
    - docker tag "$CI_REGISTRY_IMAGE:${CI_COMMIT_SHORT_SHA}" "$CI_REGISTRY_IMAGE:$TAG"
    - docker push "$CI_REGISTRY_IMAGE:$TAG"
    - docker run -d --name my-app -p 3000:3000 "$CI_REGISTRY_IMAGE:$TAG"
  only:
    - development
    - main
  environment:
    name: $CI_COMMIT_REF_NAME
